apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: serviceaccount
  name: {{ .Release.Name }}-blackduck-service-account
  namespace: {{ .Release.Namespace }}
