apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  type: NodePort
  ports:
    - targetPort: 5601
      port: 5601
      nodePort: 30601
      protocol: TCP
  selector:
    app: kibana
