apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-stack
spec:
  type: NodePort
  ports:
    - targetPort: 9200
      port: 9200
      nodePort: 30200
      name: port1
    - targetPort: 9300
      port: 9300
      nodePort: 30300
      name: port2
  selector:
    app: elasticsearch
